### ISSUE TITLE
оптимизировать показ количества новых задач

### ISSUE THREAD

**Issue by itiu** [semantic-machines/veda#100]
Текущая реализация делает периодические поиски для
извлечении информации о количестве новых задач в inbox. 
Для оптимизации по нагрузке на сервер, следует переделать, подобно функционалу нумераторов, то есть вести подсчет новых задач серверными скриптами, клиент должен считывать уже предподготовленные значения.

**Comment by karpovr** [comment]
Связана с #258

**Comment by karpovr** [comment]
Сделаны счетчики задач.
