### ISSUE TITLE
дополнить выгрузку в SQL

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#104]
Добавить в каждой таблице в БД поле created. В которое вписывать дату создания, записи реквизита.
По завершении перезалить все данные на продуктиве.

**Comment by itiu** [comment]
для добавления поля created, можно использовать SQL запрос для генерации alter table всех таблиц:

use information_schema;
select CONCAT("Alter Table `", TABLE_SCHEMA,"`.`", TABLE_NAME, "` Add Column `created` DATETIME NULL") as MySQLCMD from TABLES where TABLE_SCHEMA = "veda_db";
