### ISSUE TITLE
Дополнительная информация в Event'ах

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#105]
Требуется знать больше информации о сохраняемом документе: в какие классы (subClassOf) он входит. Данная информация нужна для корректной работы версионирования+журналирования.

**Comment by itiu** [comment]
была добавлена переменная var super_classes.
содержит строку вида:
    ["owl:Thing", "rdfs:Resource", "v-wf:Condition", "v-wf:NetElement"]

**Comment by xupyprmv** [comment]
@itiu благодарю
