### ISSUE TITLE
Дополнить функцию прерывания процесса

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#128]
Добавить в функцию прерывания процесса по документу вызов трансформации s-wf:currentNetFromIsProcess или мэппинга s-wf:map_currentNetFromIsProcess_to_transformation
Он удаляет из поля v-wf:isProcess id прерываемого процесса.

**Comment by xupyprmv** [comment]
+ возможность вызова из Task'а в сети

**Comment by xupyprmv** [comment]
Для решения этой проблемы была написана функция: interrupt_process(process)

Вызов функции прописан в обработчик прерывания маршрута. + есть возможность вызвать его через вызов кодлета "Вывести из документооборота" через Исполнитель (в Task`е).
