### ISSUE TITLE
Возможность из сети вызвать функцию Создать версию

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#130]
Возможность из сети вызвать функцию Создать версию для документа неверсионного. 
Нужно для управляемого создания срезов с документа в зависимости от его жизненного цикла.

**Comment by xupyprmv** [comment]
Для класса `v-s:Versioned` были созданы 2 подкласса :

* `v-s:AutomaticallyVersioned`
* `v-s:ManuallyVersioned`

`v-s:AutomaticallyVersioned`: версии создаются автоматически при сохранении документа
`v-s:ManuallyVersioned`: версии создаются вручную путём установки флажка `v-s:triggerVersionCreation` в значение `true`
