### ISSUE TITLE
Не открывается журнал

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#132]
Для того чтобы кнопки доп. действий корректно работали мы добавляли следующий код:

https://github.com/semantic-machines/veda/blob/884e25d481853496ea7f91bafae79077d51cd1a5/public/js/browser/individual_actions.js#L17

Но при отображении бланка документа. Например Встреча. Кнопка не журнала не работает. Т.к. форма встречи рисуется внутри формы бланка. 

Вот такие пироги.

**Comment by karpovr** [comment]
Сделано
