### ISSUE TITLE
v-s:Actor - appointment

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#133]
В классе v-s:ProcessStarted  нужно, чтоб v-s:actor был Appointment, а не person

**Comment by xupyprmv** [comment]
Я так понял эту проблему уже решили. По крайней мере v-s:actor в  v-s:ProcessStarted больше не используется.

**Comment by bychina** [comment]
При запуске Процесса Поручение (а возможно и других) при журналировании факта старта инициатор вычисляется так: Австор стартовой формы / его персон / его назначение по умолчанию. 
В ситуации, когда пользователь работает по иным назначением (не под основным) все равно журналируется так, а в сеть передается инициатор именно как автор стартовой формы.

Нужно, чтобы журналирование и инициирование происходило от имени текущего назначения пользователя.
