### ISSUE TITLE
Ошибка отображения в меню создания сети

### ISSUE THREAD

**Issue by FluffyBear** [semantic-machines/veda#139]
При заполнении полей данные отображаются 2 раза, а не 1.

**Comment by xupyprmv** [comment]
судя по всему баг плавающий, нужно поработать с редактором маршрута чтобы повторить

**Comment by FluffyBear** [comment]
![1](https://cloud.githubusercontent.com/assets/7620346/17802011/48a36ff6-65f6-11e6-8534-9979524415a1.jpg)
[https://github.com/semantic-machines/veda/blob/master/qa/testSimpleNet.js](url)
Создать-->Стартовая форма-->Заполнение полей "Для сети" и "Статус документа"-->Сохранить

**Comment by xupyprmv** [comment]
@karpovr Я думаю этот тикет можно будет закрыть, когда ты выложишь решение проблемы дублирования полей.

**Comment by karpovr** [comment]
Устранено

**Comment by FluffyBear** [comment]
@xupyprmv @karpovr [Я думаю, что это не нормально](https://saucelabs.com/beta/tests/1027e1a4416f4bae9f48e8b33395a99c/watch#66)
