### ISSUE TITLE
Добавить возможность поиска по дочерним свойствам

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#142]
Аналогично поиску по подклассам реализовать поиск по дочерним свойствам:
Поиск по подклассам сейчас работает так:
Если поисковое условие написано как `'rdf:type' == 'v-s:Document'`, то производится поиск индивидов указанного класса а также всех его подклассов. `('rdf:type' === 'v-s:Document' || 'rdf:type' === 'v-s:AdminstrativeDocument')`
Если поисковое условие написано как `'rdf:type' === 'v-s:Document'`, то производится поиск только индивидов указанного класса.

Аналогично необходимо реализовать и для свойств:
Если поисковое условие написано как `'v-s:attachment' == 'd:671hgf7d762t3g8e'`, то поисковый запрос на сервере должен преобразоваться в такой:
`('v-s:attachment' === 'd:671hgf7d762t3g8e' || 'v-s:riskAttachment' === 'd:671hgf7d762t3g8e')` 
где 'v-s:riskAttachment rdfs:subPropertyOf v-s:attachment'

Если поисковое условие написано как `'v-s:attachment' === 'd:671hgf7d762t3g8e'`, то поисковый запрос на сервере не преобразуется.

**В ходе обсуждения договорились изменить синтаксис.** 
Вместо изощренного написания различных вариантов сравнения заключать свойства и классы в квадратные скобки. При этом класс, указанный в квадратных скобках, дополняется множеством всех его подклассов, а свойство - множеством всех его дочерних свойств.

**Comment by itiu** [comment]
дабы поиск не валился, требуется решить #275
