### ISSUE TITLE
Лишние результаты поиска

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#149]
('rdf:type'=='mnd-s:Meeting')&&('v-s:copyTo'=='td:AndreyBychin-ExecutiveDirector'||'v-s:copyTo'=='td:ValeriyBushenev-TechnicalDirector')

Запрос возвращает лишние результаты, а именно индивиды, в которых вообще нет указанных значений 'v-s:copyTo'.

**Comment by itiu** [comment]
не удалось подтвердить данную ошибку (не достаточно тестовых данных)
