### ISSUE TITLE
Исправить тест проверки журнала

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#155]
Т.к. мы сделали v-s:Person нежурналируемым, нам требуется переписать тест проверки журнала.

Созадвать не v-s:Person, а v-s:Activity (журналируемый класс). Логику проверки самого журнала оставить без изменений.

**Comment by FluffyBear** [comment]
Сделано

**Comment by xupyprmv** [comment]
@FluffyBear Спасибо
