### ISSUE TITLE
Убрать валидацию для кнопки "Печатная форма"

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#159]
В шаблонах кнопки с классом "createReport" не доступны для клика, если документ, содержащий кнопку, не прошел валидацию. Нужно убрать эту проверку.
То же самое с кнопкой "Выдать задачу" - убрать валидацию

**Comment by xupyprmv** [comment]
Не уверен что это правильно. Т.к. логика отчёта или маршрута может предполагать что обязательные поля заполнены. В противном случае везде нужно будет писать защитный код, который допускает отсутствие требуемого значения.
