### ISSUE TITLE
Отремонтировать тест

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#164]
Разбртаться что не так с тестом:

https://travis-ci.org/semantic-machines/veda/builds/165738604

Если проблема в тесте - исправить. Если проблема в veda - создать дочерний тикет.

**Comment by FluffyBear** [comment]
Сделано. Проблема была в том, что поле Ответственный стало обязательным.
P.S.[Хотя выглядит не так](https://gyazo.com/bb8d4fb3635fdd3d398040d6dd6a4388)
