### ISSUE TITLE
Локализация при вводе текстовых полей

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#167]
1. Для контролов типа "multilingualText" в режиме Edit рисовать столько экземпляров, сколько включено локалей у пользователя. Отображаются друг под другом с небольшим пробелом между.
2. Каждому такому клону контрола присваивается однозначный язык ввода. Фиксируется "шильдик" языка слева.
3. Спецификация для данных полей определяется как minCardinality = 1, maxCardinality = 2
4. К таким контролам добавляем placeholder типа: "Включите две локали. Введите значение на двух языках"
5. На будущее: в режиме View если включены не все локали, а поле типа "multilingualText" имеет значения и в других языках, то рисовать рядом с контейнером восклицательный знак, наводя на который всплывает подсказка "Имеется вариант значение на другом языке. Включите соответствующую локаль".

**Comment by karpovr** [comment]
Готово
