### ISSUE TITLE
Разделение очередей почтовых рассылок и экспорта в SQL

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#168]
Нужно разделить очереди почтовых рассылок и экспорта в SQL. 
Сейчас в некоторых случаях почтовый серевер отвечает отказом, а разборщик очереди идет дальше, так как нужно выполнять экспорт в SQL.
Нужно гарантировать как выгрузку в SQL так и отправку писем

**Comment by itiu** [comment]
готово
