### ISSUE TITLE
Задача ознакомления

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#169]
1. Одиночная задача. Один вариант ответа:
- "Ок"

2. Добавить эту задачу в стандартный блок, мультикнопку "Выдать задачу" (standart-tasks кажется).

**Comment by lexiqq** [comment]
Добавить эту задачу в стандартный блок, мультикнопку "Выдать задачу" (standart-tasks кажется).

**Comment by FluffyBear** [comment]
@lexiqq Проверь пожалуйста.

**Comment by lexiqq** [comment]
Что-то у меня ничего не открылось. Я имею ввиду стартовую форму. Скриншоты прилагаю.

![default](https://cloud.githubusercontent.com/assets/9006037/21886123/714d9ae2-d8cb-11e6-8682-2644edb28f71.jpeg)
![2](https://cloud.githubusercontent.com/assets/9006037/21886132/74a42ce2-d8cb-11e6-9bb7-f08ad82695db.jpeg)

**Comment by lexiqq** [comment]
**Дополнение к задаче**: Просьба переименовать линки на эти стандартные задачи:
"Задать вопрос" в "Вопрос"
"Выдать поручение" в "Поручение"
"Выдать задачу" в "На ознакомление"

**Comment by FluffyBear** [comment]
@lexiqq Поменял линки. А у меня все [нормально работает](http://recordit.co/lVbR2GcV5Y).

**Comment by xupyprmv** [comment]
@lexiqq проверь новую версию плиз

**Comment by lexiqq** [comment]
@xupyprmv Вова, проверила. 
Линки переименованы.
Задачи выдаются, журналируются. Все хорошо. 
Только поменяйте формулировку с "Ответить на задачу" на "Ознакомиться".
![default](https://cloud.githubusercontent.com/assets/9006037/22200680/2089a520-e171-11e6-8fdc-178cc8abd8c5.png)

**Comment by FluffyBear** [comment]
@lexiqq Сделано.

**Comment by lexiqq** [comment]
а где сделано? Собралась, на локальном проверила - нету. На 59 - нету.

**Comment by FluffyBear** [comment]
@lexiqq  Исправил небольшую ошибку. Собрался. Должно работать.
