### ISSUE TITLE
Написать тест для функции комментирования

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#172]
Нужно протестировать:
1. Добавление комментария.
2. Ответ на комментарий.
3. Редактирование / удаление комментария автором. Редактирование / удаление возможно только если на комментарий не было ответов.
4. Права доступа к комментариям должны быть на только на чтение у пользователей имеющих доступ к документу.

**Примечания**
- Блок комментирования включен на личной карточке пользователя (Шаблон персоны).
- Сейчас добавлять комментарии может только админ. Права на создание обычным пользователям еще не выданы.

**Comment by FluffyBear** [comment]
А у администраторов есть такие права, что они могут удалять чужие комментарии( + если на комментарии есть ответы)?

**Comment by karpovr** [comment]
У администраторов права есть, но из вьюшки удаляются кнопки удалить / редактировать если на комментарий был дан ответ. Таким образом, админы могут удалить / отредактировать чужие комментарии, если на них еще не было ответов.

**Comment by FluffyBear** [comment]
@karpovr [Почти сделано](https://saucelabs.com/beta/tests/8d252fc040224bd4a6054e087f1319cc/watch#78). Одна проблема, у пользователя, у которого есть доступ к чтению, какие кнопки должны отображаться? Только ответить или вообще никаких? Я сначала захожу под karpovrt, а потом перехожу под bychinat, у него отображаются кнопки Ответить и Редактировать, при нажатии на Редактировать открывается меню редактирования комментария, но сохранить изменения нельзя. Мне кажется, что что-то здесь не так.

**Comment by GilyazoMV** [comment]
Если права только на чтение должна отображаться только кнопка ответить. Не было прописано что если у пользователя нет прав на редактирование то кнопка "редактировать"  удаляется. Все исправлено теперь все должно работать как надо.

**Comment by FluffyBear** [comment]
[Сделано](https://saucelabs.com/beta/tests/a03c234859ae4038a4605f8c09a7860c/watch#83)
