### ISSUE TITLE
Оптимизация выполнения интеграционных тестов.

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#178]
Во многих местах в тестах используются слипы. Нужно отрефакторить тесты и заменить где это возможно sleep на wait/until. Это нужно с целью оптимизации времени выполнения тестов.

**Comment by FluffyBear** [comment]
[+-3,5 минуты быстрее](https://saucelabs.com/beta/builds/490edfadc37c4dfea40b71b7e6764217)

**Comment by xupyprmv** [comment]
@FluffyBear Ок.
