### ISSUE TITLE
Сделать на сервере отдельную машину v8 для выполнения "долгих" скриптов по расписанию

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#180]
У объектов класса "v-s:Event" предусмотреть признак для запуска на конкретной машине.

Расписание исполнения различных скриптов предлагаю сделать с помощью программы крон.
Т.е. к примеру, в кроне по расписанию вызывается программа, которая сохраняет в базу объекты классов v-s:HourlyEvent, v-s:DailyEvent и т.п. а события в свою очередь реагируют на сохранение этих объектов.

**Comment by itiu** [comment]
готово, если нужно чтоб скрипт иполнялся в другой V8, нужно указать v-s:runAt "V8.LowPriority" ;
