### ISSUE TITLE
поправить журналирование в процессе поручения

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#182]
В процессе поручения при выборе варианта ответа "Ошибочный исполнитель", задача приходит инициатору (как нужно), а в журнале пишет, что задача снова выдалась этому же исполнителю (что неверно). Нужно исправить.

**Comment by xupyprmv** [comment]
В задаче контроля та же ошибка. На контроль уходит правильно, а в журнале прописывается что ушло инициатору.
