### ISSUE TITLE
Обработчик версий документов при сохранении

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#184]
При сохранении версии объекта необходимо помещать индивид версии в группу основного документа, чтобы у пользователя были права на версии

**Comment by karpovr** [comment]
Вовка, это надо сделать в серверном скрипте создания версии объекта.

**Comment by xupyprmv** [comment]
@karpovr 

Так вот же вроде всё есть:

https://github.com/semantic-machines/veda/blob/master/public/js/server/util.js#L343

Или там что-то напутано, вроде всё норм - версия включается в группу актуального документа

**Comment by karpovr** [comment]
Мопед не мой,...
