### ISSUE TITLE
Валидация - Досье

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#188]
v-s:ContractorProfile
0. добавить проверку уникальности ИНН 

1. Если в mnd-s:ContractorCategoryRequest mnd-s:contractorCategory =1 то обязательные к заполнению поля:
mnd-s:attachLicense
mnd-s:attachCertificateRegistrationLegal

2. Если в mnd-s:ContractorCategoryRequest mnd-s:contractorCategory =2 то обязательные к заполнению поля:
mnd-s:attachLicense
mnd-s:attachCertificateRegistrationLegal

3. Если в mnd-s:ContractorCategoryRequest mnd-s:contractorCategory =3 то обязательные к заполнению поля:
mnd-s:attachLicense
mnd-s:attachCertificateRegistrationLegal
mnd-s:attachCertificateTaxRegistration
mnd-s:attachExcerptFromEGRUL
mnd-s:attachAppointingOrder
mnd-s:attachWarrant

4. Если в mnd-s:ContractorCategoryRequest mnd-s:contractorCategory =4 то обязательные к заполнению поля:
mnd-s:attachLicense
mnd-s:attachCertificateRegistrationLegal
mnd-s:attachCertificateTaxRegistration
mnd-s:attachExcerptFromEGRUL
mnd-s:attachAppointingOrder
mnd-s:attachWarran
mnd-s:attachTaxReport
mnd-s:attachAccountBalance
mnd-s:attachInsurancePayments
mnd-s:attachDocConfirmUseAddresses
mnd-s:attachDocSpecialTaxSystem
mnd-s:attachSubcontract
mnd-s:attachSubcontractorInteraction

5. Если в mnd-s:ContractorCategoryRequest mnd-s:contractorCategory =5 то обязательные к заполнению поля:
mnd-s:attachLicense
mnd-s:attachCertificateRegistrationLegal
mnd-s:attachCertificateTaxRegistration
mnd-s:attachExcerptFromEGRUL
mnd-s:attachAppointingOrder
mnd-s:attachWarran
mnd-s:attachTaxReport
mnd-s:attachAccountBalance
mnd-s:attachInsurancePayments
mnd-s:attachDocConfirmUseAddresses
mnd-s:attachSubcontract
mnd-s:attachSubcontractorInteraction

6. Если в mnd-s:ContractorCategoryRequest mnd-s:contractorCategory =6 то обязательные к заполнению поля:
mnd-s:subContractorOf

7. Если в mnd-s:ContractorCategoryRequest в поле v-s:hasClassifierOKVED начинается на 49, 50, 51, 52, 53 то дополнительно к предыдущим -  обязательные к заполнению поля:
mnd-s:attachDocConfirmUseTransport (обязательно к категориям 1-5)

8. Если в mnd-s:ContractorCategoryRequest в поле v-s:hasClassifierOKVED начинается на 02 то дополнительно к предыдущим -  обязательные к заполнению поля:
mnd-s:attachDocConfirmUseWood   
mnd-s:attachDocConfirmUseForestryEquipment

**Comment by karpovr** [comment]
Готово
