### ISSUE TITLE
Тесты по делегированию полномочий

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#190]
Разработать тесты по делегированию полномочий.

Делегирование работает следующим образом. Пользователь "Доверитель" создает в системе Документ "Заявка на делегирование". Указывает в заявке "Заместителя", отмечает несколько  должностей, которые он хочет делегировать, указывает срок действия делегирования полномочий.

После сохранения документа у "Заместителя" в списке доступных должностей (справа сверху) должны появиться новые делегированные должности. 

При выборе делегированной должности в списке задач и календаре должны отображаться задачи на эту должность. Независимо от выбранной должности "Заместитель" должен получить и права на объекты, к которым имеет доступ "Доверитель".

Проверка делегирования задач:
1) Направляем задачу доверителю. В списке задач доверителя есть задача, в списке задач потенциального заместителя нет задачи.
2) Доверитель создает заявку на делегирование. Заместитель выбирает делегированную должность из списка.  В списке задач заместителя есть задача.

Проверка делегирования прав на объекты:
1) Доверитель создает какой-нибудь документ. Доверитель имеет доступ к документу, потенциальный заместитель не имеет доступа.
2) Доверитель создает заявку на делегирование. Доверитель и заместитель имеют равный доступ к документу.

**Comment by FluffyBear** [comment]
@karpovr Не понимаю в каком списке(не понимаю как его открыть) после создания заявки на делегирование у "Заместителя" должны появиться делегированные должности. И как еще после создания заявки удалить ее. Не сразу, а после того как уже вышел из редактора создания. Я нахожу заявку, но не могу в нее войти, чтобы редактировать/удалить.

**Comment by FluffyBear** [comment]
[Делегирование прав на объекты](https://saucelabs.com/beta/tests/cc6f22e172cf4c11a6d73f50747b4e50/watch#229) И еще, после того как прошло время(dateTo) права все еще остаются у заместителя.

**Comment by karpovr** [comment]
@FluffyBear Ага, понятно, эти возможности доступны только если включить проект Монди. Там есть и списки и переключатели должностей. Тогда можно отложить реализацию этого теста, пока эти возможности не будет перенесены в проект veda.

**Comment by FluffyBear** [comment]
Ок

**Comment by FluffyBear** [comment]
@karpovr [Делегирование задач](https://saucelabs.com/beta/tests/6143493eb8144e17b5c4412c0a4756ad/watch#323)

**Comment by karpovr** [comment]
Принято
