### ISSUE TITLE
выгрузка в ttl - оптимизировать количество префиксов

### ISSUE THREAD

**Issue by itiu** [semantic-machines/veda#205]
при выгрузке индивида в ttl выгружаются префиксы к которым выгружаемый индивид не имеет отношение (т.е. все известные префиксы). Это приводит к невозможности выгрузки в ttl если хоть в одном префиксе есть проблемы.

**Comment by karpovr** [comment]
Исправлена функция выгрузки в TTL

**Comment by itiu** [comment]
После исправления, количество выгружаемых префиксов не изменилось: выгружаются префиксы к которым выгружаемый индивид не имеет отношение
