### ISSUE TITLE
права в задаче Отклонено

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#207]
Вариант ответа "Отклонено" должен выводить документ из документооборота, чтоб у пользователя, которому выдается задача "Доработать", были права на редактирование.

**Comment by xupyprmv** [comment]
Решили делать по другому. Кнопка "редактировать" не будет подчиняться правилу "Если запущен маршрут то нельзя", а будет просто проверять права на редактирование.

Таким образом мы саможем выдавать права редактирования по маршруту. Единственный минус - те кто может редактировать смогут редактировать документ даже если он запущен по маршруту. И так будет пока мы не реализуем систему многоуровневых прав.
