### ISSUE TITLE
Проблемы с логином

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#21]
1) Нет реакции на неправильный пароль
2) Когда сессионный билет просрочен система не предлагает перелогиниться, а просто отображает пустое окно с полупустой шапкой
3) Когда сессионный билет просрочен можно по меню вызывать разные функции и они не предлагают переголиниться, а функция Документ  / Найти - перебрасывает на страницу Логина

**Comment by karpovr** [comment]
Fixed in fa5b6162c1c494c46e679409031e80de73bc1ec6

**Comment by xupyprmv** [comment]
4) В форме логина по умолчанию попадаем на поле пароль. Нужно сделать так, чтобы мы попадали на поле логин.
