### ISSUE TITLE
Исправить тест testPager.js

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#210]
Пример:
https://travis-ci.org/semantic-machines/veda/builds/178838603

Видимо, изменилось количество данных выдаваемых в поисковом запросе (изменилась онтология), и кнопка со второй страницей пейджера переместилась ниже.

Может изменить условие и нажимать по координатам, а искать кнопку на странице и нажимать её при условии, что она видна?

**Comment by FluffyBear** [comment]
[Доделано](https://saucelabs.com/beta/tests/9e401485f79344178fcda160d8ee1ce8/watch#64)
