### ISSUE TITLE
Тестирование 

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#214]
Нам нужен тест универсального маршрута.

http://live.semantic-machines.com/#/s-wf:net_coordination

Для этого нам нужно сделать:

1) Создать (или использовать существующий) тестовый тип, привязать его к запуску универсального маршрута.

2) Создать тест который будет проверять работу всех пунктов задачи:
2.1) Выдача самой задачи
2.2) Возможность ответа каждым из способов
2.3) Выдача задачи контроля: возможность вернуть, делегировать или согласовать задачу
2.4) Задача доработки: возможность вернуть, делегировать или согласовать задачу

**Comment by FluffyBear** [comment]
#259 #260
