### ISSUE TITLE
Возможность указывать должность в стартовых формах

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#221]
В случаях, когда автоматически заполняется стартовая форма, часто нужно сразу указывать должность (роль). 
При ручном заполнении пользователями пока можно оставить только Назначения.
Нужно, чтобы сеть различала и обрабатывала ситуации, когда в качестве исполнителя указан как Назначение так и Должность. Задача направляется на Должность в любом случае.
Проверить, Возможно в стартовой форме поля не расчитаны на отображение Должности.

**Comment by xupyprmv** [comment]
Данная возможность поддерживается "из коробки".
