### ISSUE TITLE
Резолюция

### ISSUE THREAD

**Issue by elenakarpova** [semantic-machines/veda#222]
Кнопки Резолюция НУ, СЭБ и ПУ неодинаковой длины.
Переименовать указанные кнрпки в Заключение НУ, СЭБ, ПУ.
Дата принятия решения - поле никак не названо. ?

**Comment by GilyazoMV** [comment]
Все готово.
"Дата принятия решения - поле никак не названо. ?" 
Тут так и задумано было(мы подумали что все логично, если нет можно поменять).
