### ISSUE TITLE
Ошибка в журнале

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#223]
![16000081_ _](https://cloud.githubusercontent.com/assets/9006037/20968444/a0fc1446-bc95-11e6-94e8-bb3b044f7de0.png)

При старте универсального маршрута (задать вопрос). в журнале не отображается изначальный комментарий отправителя. Хотя в сети он есть
Например, идея 16000081. Задача от Рыжковой к Сотничуку.

**Comment by xupyprmv** [comment]
Невозможно повторить. Возможно уже исправили.
