### ISSUE TITLE
Делегирование - обновление

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#224]
1. Сделать две заявки на делегирование (Заявка 1 - для пользователей, Заявка 2 - для нас)
![img_20161208_101452](https://cloud.githubusercontent.com/assets/9006037/21001383/0dd61c88-bd31-11e6-89ea-aeccff168a89.jpg)
2. В сформированных по заявкам Назначениям формировать красивый label
3. Права на создание заявки 1 - всем.
Права на создание заявки 2 - только нам.

**Comment by karpovr** [comment]
Готово.

**Comment by bychina** [comment]
1. Укоротить формируемый id для назначений, создаваемых из заявок на делегирование
2. Добавить возможность вводить Label (в 2-х языках) для будущего назначения в Системную заявку
3. Автоматически формировать label (в 2-х языках) для назначений, формируемых из Пользовательских заявок. Шаблон:  Имя Фамилия: Должность (делгировано)

**Comment by karpovr** [comment]
Сделано.
