### ISSUE TITLE
Замечания по Контрактам, Допам и Заявке на контракт

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#225]
**Для заявки на контракт**
1. Отчет о вЫполнеии - орфографическая ошибка
2. Журнал не кликается.
3. Для полей Инициатор, Проект, Перечень потенциальных организаций, Контракт - убрать признак dropdown и добавить placeholder "Начните ввод и выберите значение"
4. Убрать кнопку "Печатная форма"
5. Нет реестра Заявок на контракт

**Для Контракта**
1. Поля Тема, Обоснование - сделать multylanguage
2. Поле Категория бюджета на view двоится значение.
3. Убрать кнопку "Печатная форма"
4. Не отрабатывает backwardLink для вложенных документов

**Для Доп соглашения**
1. Вид Документа - неправильный QuaeryPrefix (правильный в xls таблице)
2. Для полей Заинтересованная сторона, Инициатор, Ответственное подразделение - убрать признак dropdown и добавить placeholder "Начните ввод и выберите значение"
3. Для поля Заинтересованная сторона - добавить ограничение только Организации
4. Для полей Инициатор, Ответственное подразделение - добавить ограничение только Department
5. Поля Тема, Обоснование - сделать multylanguage
6. Убрать кнопку "Печатная форма"
7. Не отрабатывает backwardLink для вложенных документов

**Comment by lexiqq** [comment]
**Для Контракта**
не проставляется нумератор, не создается вообще Scope. Нужно проверить скрипт вызывающий нумератор в шаблоне контракта.
v-s:hasNumeration mnd-s:registrationNumberMapperForContract ;

**Comment by GilyazoMV** [comment]
Вот в этих классах нет, label (То есть он есть но явно пользователями не заполняется так что надо заполнить автоматом напиши какие поля и поставь мне задачу). 
mnd-s:ContractRequest
mnd-s:Contract
mnd-s:AdditionalAgreement

Далее по задаче: 

**Для заявки на контракт**
2. Журнал не кликается.(у меня все кликается не знаю в чем проблема)

**Для контракта**
2. Поле Категория бюджета на view двоится значение.(враки у меня все норм).
4. Не отрабатывает backwardLink для вложенных документов(тут  конкретно что не работает ?)

**Для Доп соглашения**
7. Не отрабатывает backwardLink для вложенных документов тут  конкретно что не работает ?)



По поводу нумератора все работает сделал. По поводу автозаполнения ответственного подразделения в RCFA тоже сделано.

**Comment by lexiqq** [comment]
label'ы для mnd-s:ContractRequest, mnd-s:Contract, mnd-s:AdditionalAgreement - в файле controlled dictionary. Остальные замечания - принимаются и снимаются.

**Comment by GilyazoMV** [comment]
готово
