### ISSUE TITLE
Аудит внутренний перевести на комплексный процесс

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#231]
Нужно перевести документ Аудит внутренний на комплексный процесс. 
Первый уровень согласования предзаполнен должностью от Буслаев П.В.

**Comment by xupyprmv** [comment]
Просто добавить поле согласующий на форму (по аналогии со встречей) и заполнить его Appointment'ом Буслаева

**Comment by karpovr** [comment]
Сделано 16.12.2016
