### ISSUE TITLE
Доработки по Заявке на контракт, контракту, доп соглашению.

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#233]
1. Добавлен нумератор mnd-s:registrationNumberMapperForContractRequest. Добавить скрипты в шаблон Заявки, чтоб отрабатывал нумератор.

2. Написать скрипт для автозаполнения Организации из Контрагента в связках v-s:customer и v-s:supplier в шаблонах Заявка на контракт, Контракт, Доп соглашение.

3. В этих же связках везде поменять местами вверху Контрагент, вниз Организация.

4. Сделать реестр Заявок на контракт.

**Comment by lexiqq** [comment]
5. В заявке на контракт добавить скрипт: если "Вид документа" = Доп соглашение, то поле "Контракт" обязательно.

6. В заявке на контракт, кнопку с bundle "Отчет о выполнении заявки" заменить на кнопку с названием класса "Выполнение заявки на контракт"

**Comment by GilyazoMV** [comment]
готово.

**Comment by lexiqq** [comment]
в Заявке на контракт добавить скрипт, который проверяет. чтоб в одном из полей v-s:customer или v-s:supplier было вписано значение d:org_50001654 (АО Монди).
Выдавать сообщение по принципу валидации - обводить красным оба поля и писать коммент.

в Контракте и Допсоглашении, аналогичный скрипт, но проверяет наличие d:org_50001654 (АО Монди) в трех полях  v-s:customer или v-s:supplier или v-s:stakeholder

**Comment by lexiqq** [comment]
в Заявке на контракт поле v-s:hasContract отрисовывать в виде таблицы полей Контракта:
v-s:registrationNumber | v-s:theme | v-s:dateTo | v-s:dateFact

**Comment by lexiqq** [comment]
Навесить label на заявку на контракт согласно строке 589

**Comment by GilyazoMV** [comment]
Лабел пока только из темы. там сложно все завтра сделаю

**Comment by lexiqq** [comment]
Поле v-s:dateTo заполнять датой **now() + 30 дней**

**Comment by lexiqq** [comment]
Добавить скрипт: Поле v-s:initiator заполнять подразделением создателя v-s:creator.

**Comment by GilyazoMV** [comment]
Все готово.
Лабел пока только из темы. там сложно после обеда сделаю.

**Comment by GilyazoMV** [comment]
Полностью все готово.  и даже лабел.
