### ISSUE TITLE
RCFA Замечания

### ISSUE THREAD

**Issue by GilyazoMV** [semantic-machines/veda#238]
3.После выдачи поручения из гипотезы, как вернуться в форму RCFA?

**Comment by GilyazoMV** [comment]
7.При выдачи поручения из гипотезы, поручение ни где не отображается, должно отображаться и в журнале и в самой гипотезе.

**Comment by karpovr** [comment]
3 пункт выполнен. 7 пункт Вовкин.

**Comment by xupyprmv** [comment]
7 выполнен. Коммит в DMSC репо.
