### ISSUE TITLE
Отремонтировать тесты с использованием выпадающих списков

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#239]
После добавления паузы в полнотекстовых поисках с выпадающими списками, перестали проходить тесты использующие этот контрол. Визуально на видео ошибки нет (список выпадает, нужные значения есть).

**Comment by xupyprmv** [comment]
@FluffyBear Получилось повторить?

**Comment by FluffyBear** [comment]
Слипы расставил. Наиболее простой способ. Можно конечно обращаться к элементам, пока они не появятся и самому обрабатывать эксепшн, но это такое себе.
