### ISSUE TITLE
Настройка органичения на размер и тип прикрепляемого файла

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#242]
Добавить возможность настройки для полей типа файл: органичение на размер и тип прикрепляемого файла.
Аналогично СЭД

**Comment by karpovr** [comment]
Готово 9ce9012f4056176d6183b4baaa79d9d0cc3703ef

**Comment by karpovr** [comment]
Добавлена возможность ограничения размеров и типов загружаемых файлов.
Реализовано с помощью спецификаций.
Свойства: "v-ui:maxFileSize", "v-ui:acceptedFileType"

Пример:
mnd-s:TestSpecAttIdea
  rdf:type v-ui:ObjectPropertySpecification ;
  rdfs:label "Cпецификация свойства v-s:attachment для класса mnd-s:Idea"@ru ;
  rdfs:label "v-s:attachment property specification for mnd-s:Idea class"@en ;
  v-ui:forClass mnd-s:Idea ;
  v-ui:forProperty v-s:attachment ;
  v-ui:maxCardinality "100"^^xsd:integer ;
  v-ui:maxFileSize "5"^^xsd:integer ;
  v-ui:acceptedFileType ".doc,.mp3"^^xsd:string ;
.
