### ISSUE TITLE
Доработки Выполнение заявки на контракт (mnd-s:ContractRequestReport)

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#243]
1. В документе mnd-s:ContractRequestReport внизу отобразить документ из поля  v-s:backwardTarget с шаблоном по умолчанию, то есть целиком
2. Убрать поле Регистрационный номер
3. Поля Вид документа и Контракт поменять местами
4. Добавить поле mnd-s:possibleContractorList 

5. При создании mnd-s:ContractRequestReport из mnd-s:ContractRequest должны копироваться следующие поля: v-s:hasDocumentKind, v-s:hasContract, mnd-s:possibleContractorList

**Comment by GilyazoMV** [comment]
готово

**Comment by lexiqq** [comment]
Нужно добавить в Заявку на контракт новый справочник v-s:hasContractObject.
После поля Вид обязательств.

**Comment by GilyazoMV** [comment]
Готово.
