### ISSUE TITLE
Сверстать карточку претензий

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#246]
класс называется mnd-s:Claim

**Comment by lexiqq** [comment]
для реквизита mnd-s:hasClaimCircumstance
выводить композицию v-s:shortLabel | rdfs:label

**Comment by GilyazoMV** [comment]
визуально поля все есть. надо грамотно расположить желательно.

**Comment by lexiqq** [comment]
Прикрутить к претензии запуск Комплексной обработки. Для этого добавить в шаблон скрипт обработки кнопки Отправить. Пример взять из шаблона mnd-s:RequestWasteWaterDischargeTemplate

**Comment by GilyazoMV** [comment]
Готово.

**Comment by lexiqq** [comment]
1. поля v-s:sender и v-s:recipient - сделать обязательными
2. rdfs:label формировать так: 
[v-s:sender].[v-s:shortLabel] - v-s:registrationNumberOut - [v-s:recipient].[v-s:shortLabel] - v-s:registrationNumberIn
3. rdfs:label отображать вверху рядом с названием класса. Внутри карточки нигде отображать не надо.

**Comment by lexiqq** [comment]
Нужен реестр внешних претензий. Пока выведем в параметрах поиска и в результатах поиска эти поля:
v-s:sender,  v-s:registrationNumberOut,  v-s:registrationDateOut
v-s:recipient, v-s:registrationNumberIn, v-s:registrationDateIn
v-s:claimDescription,  v-s:dateFrom,  v-s:dateTo

**Comment by GilyazoMV** [comment]
готово.  rdfs:label все таки нужен  из обязательных полей. ибо все тормозит. Если это пиринципиально ( rdfs:label из не обязательных полей) то подумаю как сделать чтоб не тормозило.  сейчас  rdfs:label=v-s:sender+v-s:recipient;

**Comment by GilyazoMV** [comment]
лабел работает =)
