### ISSUE TITLE
testAttachment

### ISSUE THREAD

**Issue by FluffyBear** [semantic-machines/veda#249]
Я пытаюсь скачать файл(Просто захожу в граф и нажимаю кнопку 'Экспорт в ttl'). И при нажатии ничего не происходит. [Меню -> Граф](https://saucelabs.com/beta/tests/1850dfd9c4f24663a3d33766826a29a8/watch#66), [Администратор -> Граф](https://saucelabs.com/beta/tests/3f6669f30dee45e584e44aa99649bc80/watch#64)

**Comment by FluffyBear** [comment]
Такое дело, собрал новый билд, кнопка 'Экспорт в ttl' также не работала в этих графах. Открыл другой граф. [Меню -> Поиск -> Персона -> Администратор -> Граф](https://saucelabs.com/beta/tests/f141e6da0b4e4e4ea6885cddcfcad490/watch#99), кнопка работает. По тестам было также. Поменял граф, все проходит

**Comment by xupyprmv** [comment]
:shipit:
