### ISSUE TITLE
testRights

### ISSUE THREAD

**Issue by FluffyBear** [semantic-machines/veda#250]
Начиная с билда [#2460](https://saucelabs.com/beta/tests/c8e7b894459b47f18879f2a9c976daa5/watch#198) и до билда [#2471](https://saucelabs.com/beta/tests/24fbedc480f641b1934046593208c9e2/watch#239) testRights падал. Это происходило так: 1. Я логинился под karpovrt, создавал персону, проверял, что она находится 2. Логаутился со страницы поиска. 3.Логинился под bychinat, сразу попадал на страницу поиска и проверял, что в поиске не найдется персоны. 4. Создавал новую персону. 5. Логаутился со страницы просмотра созданной персоны. 6. Логинился опять под karpovrt и все падало, ничего не загружалось. 
Но потом, я после проверки созданной персоны, перехожу на Welcome страницу и делаю логаут. Пытаюсь залогиниться под karpovrt, все загружается, тест проходит. Словить/повторить баг не получилось. Проясните ситуацию, пожалуйста, а то я не понимаю.

**Comment by FluffyBear** [comment]
То же самое было в [testDelegationDocument](https://saucelabs.com/beta/tests/48fbcc4a3db94e6aa69af18baa8be1b4/commands#202) Я создавал заявку на делегирование, сохранял и после этого логаутился. Логинился, по идее должна загрузиться созданная заявка, но ничего не загружалось. Помог тот же переход на Welcome шаблон.

**Comment by karpovr** [comment]
Саш, ничего конкретного сказать не могу. Если баг не повторяется, диагноз поставить очень сложно.

**Comment by FluffyBear** [comment]
Ладно, может получиться словить.
