### ISSUE TITLE
Системные реквизиты в реестрах

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#254]
Добавить в шаблоне параметров поиска блок с системными реквизитами для следующих реестров:

mnd-s:ContractorProfileRegistry
mnd-s:ContractorCategoryRequestRegistry
mnd-s:ContractorCategoryDecisionRegistry
mnd-s:AuditSafetyRegistry
mnd-s:AuditSafetyActionRegistry
mnd-s:AuditSafetyAnnualPlanRegistry
mnd-s:AuditInternalAnnualPlanRegistry
mnd-s:AuditQualityRegistry
mnd-s:AuditQualityAnnualPlanRegistry
mnd-s:ActFailureRegistry
mnd-s:ActFailureActionRegistry
mnd-s:RequestWasteWaterDischargeRegistry
v-s:RequestDelegationRegistry

**Comment by GilyazoMV** [comment]
Готово
