### ISSUE TITLE
Тест универсального маршрута. Этап 1

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#259]
Доработать тест комплексного маршрута.

По сути универсальный маршрут - это каждый из квадратов комплесного.

Будем тестировать на примере Поручения 2:

**Проверка возможности разных ответов на задачу.**

1) Ответить на задачу - перенаправить

2) От нового исполнителя ответить - не мне

3) От инициатора отправить задачу на доработку

4) Ответить не выполнено

5) От инициатора отправить задачу на доработку

6) Ответить выполнено

(До этого был только пункт 6 по сути, теперь цепочка будет расширена)

П.С. Как вариант можно вытащить тест универсального в отдельный тест и запускать при помощи запуска стартовой формы просторого маршрута (Full версия). Просто для того чтобы тест был не слишком огронмный.

**Comment by FluffyBear** [comment]
[Сделано](https://saucelabs.com/beta/tests/381d330ed7134f15ac1853ca16e81474/watch#1246)
