### ISSUE TITLE
Тест универсального маршрута. Этап 2

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#260]
Доработать тест тест этапа 1.

Добавить контролирующего в  форму старта  Поручения  2.

После последнего успешного ответа (пункта 6 из этапа 1). Маршрут не завершится а уйдёт на контроль.

1) Контролирующий пернаправляет задачу другому К2

2) К2 отправляет на доработку

3) Задача приходит исполнителю, он опять отвечает "Исполнено"

4) Контролирующий подтверждает

5) Маршрут завершается.

**Comment by FluffyBear** [comment]
[Сделано](https://saucelabs.com/beta/tests/5dcd349bebfa4b8aba4a26fa5eb20c4a/watch#1476)
