### ISSUE TITLE
Выбор поставщика - доработки

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#262]
1. В шаблоне класса mnd-s:TenderProcedure (Выбор поставщика) вместо поля v-s:hasDocumentKind разместить поле v-s:hasContractScope

2. В шаблоне класса mnd-s:TenderProcedure добавить поле v-s:theme с самого верху.

3. В шаблоне класса mnd-s:TenderProcedure добавить поле v-s:description внизу после таблички.

4. При создании mnd-s:TenderProcedure из Заявки на контракт, не копировать поле v-s:hasDocumentKind,  а копировать поле v-s:hasContractScope. 
И копировать поле v-s:theme.  И копировать поле v-s:description. 

4. В шаблон Выбор поставщика добавить кнопку Отправить и привязать комплексный маршрут

**Comment by lexiqq** [comment]
В шаблоне Заявка на контракт справа в блоке кнопок добавить две кнопки "Создать Контракт" и "Создать доп соглашение".
По которым соответственно открываются карточки Контракта и Доп соглашения, у которых поле mnd-s:hasContractRequest заполняется текущим документом

**Comment by GilyazoMV** [comment]
Готово кроме заполнения поля s:hasContractRequest. Там какой то косяк надо подумать.

**Comment by GilyazoMV** [comment]
готово
