### ISSUE TITLE
Автоматическое заполнение поля v-s:responsibleDepartment в Заявке

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#263]
в Заявке на контракт поле v-s:responsibleDepartment перенести в конец карточки, 
сделать read-only и написать скрипт, который автоматически будет его заполнять, согласно алгоритму:

1.	Если v-s:hasContractObject = d:379cc929f78f4a4e84f36a9f3830d846 
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:379cc929f78f4a4e84f36a9f3830d846
	то v-s:responsibleDepartment = d:mondi_department_50003330 (Сл. закупки и продажи лесопродукции УЛО)

2.	Если v-s:hasContractObject = d:5af63e5bbeb54c4a86c2bc72fb4208a5 (целлюлоза)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:5af63e5bbeb54c4a86c2bc72fb4208a5
		ИЛИ v-s:hasContractObject = d:3e77773be122494085d07da25fe20076 (Бумага на втор)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:3e77773be122494085d07da25fe20076
		ИЛИ v-s:hasContractObject = d:d8cf8f89a0694bf9b462deb1bc6d09ab (технологич химикаты)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] =  d:d8cf8f89a0694bf9b462deb1bc6d09ab
		ИЛИ v-s:hasContractObject = d:f1bba7b333d14ea582942f7d1e1c97c5 (Вспомогательные вещества)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] =  d:f1bba7b333d14ea582942f7d1e1c97c5
		ИЛИ v-s:hasContractObject =  d:61c11dd2137e4916a94eab49ac88565b (Крахмал)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] =   d:61c11dd2137e4916a94eab49ac88565b
		ИЛИ v-s:hasContractObject =  d:d63df9806ea84691a4587f65cc73a65b (Наполнитель)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] =   d:d63df9806ea84691a4587f65cc73a65b
		ИЛИ v-s:hasContractObject =  d:1b89d9d556804828818399207ddf1114 (Пигменты покровные)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] =   d:1b89d9d556804828818399207ddf1114
	то v-s:responsibleDepartment = d:mondi_department_50003710 (Отдел закупки осн.производствен.матер.УЗ)

3. 	Если v-s:hasContractObject = d:43e7ae6b17d34fcd9e58613be049df91 (Вода)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:43e7ae6b17d34fcd9e58613be049df91
   		ИЛИ v-s:hasContractObject = d:e0de239b29c34ec3afaf25b0554893cb (Энергия)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:e0de239b29c34ec3afaf25b0554893cb
   		ИЛИ v-s:hasContractObject = d:dd56fab4a4f444cd925ee1c99c2fb8ac (Топливо)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:dd56fab4a4f444cd925ee1c99c2fb8ac
	то v-s:responsibleDepartment = d:mondi_department_50003710 (Отдел закупки осн.производствен.матер.УЗ)

4. 	Если v-s:hasContractObject = d:a6f80eb26bbb4ffcb56691ac5ba511da ()
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:a6f80eb26bbb4ffcb56691ac5ba511da
		ИЛИ v-s:hasContractObject = 	d:b98840ca4b8f47c2b32a12cc01906208 (краски)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = 	d:b98840ca4b8f47c2b32a12cc01906208
		ИЛИ v-s:hasContractObject = d:89e8c38865c54b4eaffc5df506fca683 (краски 2)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:89e8c38865c54b4eaffc5df506fca683
		ИЛИ v-s:hasContractObject = d:ed715abf1d80407588efa47ba3c75179 (краски 3)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:ed715abf1d80407588efa47ba3c75179
		ИЛИ v-s:hasContractObject = d:be0101cddba94f7aaa060aaa058e8a4e (материалы для печати)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:be0101cddba94f7aaa060aaa058e8a4e
		ИЛИ v-s:hasContractObject = d:dbf8b6d152f04d20bd1dcae8e163db51 (Печатные химикаты )
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:dbf8b6d152f04d20bd1dcae8e163db51
		ИЛИ v-s:hasContractObject = d:51abdbbe8ac94556b4e0455e2374a816 (полипропилен)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:51abdbbe8ac94556b4e0455e2374a816
		ИЛИ v-s:hasContractObject = d:a8f18e17ce7647788e8b27e712c5ee39 (силиконы)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:a8f18e17ce7647788e8b27e712c5ee39
		ИЛИ v-s:hasContractObject = d:7230749746e943fdb610626e763742fb (Standard PE)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:7230749746e943fdb610626e763742fb
		ИЛИ v-s:hasContractObject = d:0ff1b5be8bd849f08ca2bf4ed53b7a16 (клеи)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:0ff1b5be8bd849f08ca2bf4ed53b7a16
	то v-s:responsibleDepartment = d:mondi_department_50003676 (ГрЗакупки Упаков Матер и Тр Усл ОЗВМУ УЗ)

5. 	Если v-s:hasContractObject = d:c7613d1b104d4ffa86a14ee795cdd792 (Материалы горюче-смазочные)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:c7613d1b104d4ffa86a14ee795cdd792
		ИЛИ v-s:hasContractObject = d:987c0881a6464112b1a25c25b4b3b67e (Электрика, электроника)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:987c0881a6464112b1a25c25b4b3b67e
		ИЛИ v-s:hasContractObject = 	d:e04858bc7da54cc9a6b7d44f8ce76731 (Механика)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:e04858bc7da54cc9a6b7d44f8ce76731
		ИЛИ v-s:hasContractObject = 	d:ca2c0746e181466da8999722c98d4c0f (Материалы строительные)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:ca2c0746e181466da8999722c98d4c0f
	то v-s:responsibleDepartment = d:mondi_department_50003429 (Гр.зак.оборуд.зап.частей, матер.ОТЗ УЗ)

6. 	Если v-s:hasContractObject =  d:916b0a3222d144128b3bfc05a690ccd0 (Расходные материалы)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:916b0a3222d144128b3bfc05a690ccd0
	то v-s:responsibleDepartment = d:mondi_department_50003136 (Отдел технических закупок УЗ)

7. 	Если v-s:hasContractObject =  	d:6aa0a08ef0fc4aeca55e3f283dc2a9fd (Технические услуги)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:6aa0a08ef0fc4aeca55e3f283dc2a9fd
	то v-s:responsibleDepartment = d:mondi_department_50003430 (Гр.закупки услуг ОТЗ УЗ)

8. 	Если v-s:hasContractObject =  	d:b3e9e60c3ecb4ca98ab31179d162815f (Косвенные расходы)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:b3e9e60c3ecb4ca98ab31179d162815f
	то v-s:responsibleDepartment = d:mondi_department_50003675 (ГрЗакупВспомЛесотранспУслугМатер ОЗВМ УЗ)

9. 	Если v-s:hasContractObject = d:0c350969f2b8449c93594ee767cb27ef  (Транспорт)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:0c350969f2b8449c93594ee767cb27ef 
	то v-s:responsibleDepartment = d:mondi_department_50003589 (Отдел закупки вспом.матер. и услуг УЗ)

10. 	Если v-s:hasContractObject = d:0c2031235b5248819f19dbd1cdebb307	(CAPEX)
		ИЛИ  [v-s:hasContractObject].[v-s:hasParentLink] = d:0c2031235b5248819f19dbd1cdebb307	
	то v-s:responsibleDepartment = d:mondi_department_50003579 (Группа по капитальным вложениям ОТЗ УЗ)

**Comment by GilyazoMV** [comment]
тут я тупо перенес вниз то поле какое надо перенести. на сегодня, мои полномочия  все !

**Comment by lexiqq** [comment]
Если поле v-s:hasBudgetCategory = 'd:add478ffd-4996-ca11-8d8c-51bf810357c7' (CAPEX), 
то перечисленные поля отображаются, ИНАЧЕ скрываются.
v-s:hasSector, mnd-s:contractRequestEquipmentDescription, mnd-s:contractRequestMaterialsDescription, mnd-s:contractRequestServicesDescription.
Можно объединить эти поля в какой-то общий div

**Comment by GilyazoMV** [comment]
Все готово.
