### ISSUE TITLE
Изменения в Контракте и Допе

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#264]
1. В Контракте и Допе поле v-s:initiator заполнять автоматически подразделением автора, как в заявке

2. В Контракте и Допе если v-s:hasBudgetCategory= (CAPEX), то mnd-s:hasContractSpecification отображать, ИНАЧЕ скрыть.

3. При создании Контракта и Доп соглашения из Заявки копировать следующие поля:
v-s:theme
v-s:initiator
v-s:hasBudgetCategory
v-s:rationale
v-s:hasProject
v-s:hasObligationKind
v-s:customerContractor
v-s:customer
v-s:supplierContractor
v-s:supplier
v-s:hasContract
v-s:responsibleDepartment

**Comment by GilyazoMV** [comment]
Готово кроме валидации вложенного шаблона mnd-s:hasContractSpecification . Это поле пока не обязательное. как Рома разберется будет.
