### ISSUE TITLE
Скрипт по обновлению номеров в аудитах и встречах

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#279]
Написать и прогнать на продуктиве скрипт, обновляющий 
1. Аудиты безопасности и обновляющий номера в его мероприятиях.
2. Встречи и обновляющие номера в ее мероприятиях, которые находятся в поле v-s:hasAction (mnd-s:hasPreviousAction - не трогать!!)

**Comment by karpovr** [comment]
Сделано
