### ISSUE TITLE
не проходит тест

### ISSUE THREAD

**Issue by itiu** [semantic-machines/veda#280]
https://saucelabs.com/beta/tests/9ac7583f01db4e65a0c7013a1e286de4/watch#204

**Comment by FluffyBear** [comment]
@itiu  Пока просто убрал тест, [тот же баг](https://github.com/semantic-machines/veda/issues/250). Не понимаю в чем дело, пока не получилось исправить.

**Comment by karpovr** [comment]
@FluffyBear Саша, а может стоит в начале тестирования в Chrome нажать клавишу F12 (и перейти на вкладку "console") чтобы открылась его консоль? По крайней мере мы увидим ошибку в консоли браузера. Они обычно говорящие.

**Comment by FluffyBear** [comment]
@karpovr Ок. Я что-то об этом не подумал даже.

**Comment by FluffyBear** [comment]
@karpovr Что-то у меня не получается открывать консоль. Но когда работал, словил похожий баг, сделал логаут, потом логин и ничего не загрузилось. Открыл консоль, [там вот это было.](https://gyazo.com/bfad03f917158f6ead5c151fee273986)
