### ISSUE TITLE
В шаблоне Досье правка

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#281]
В шалоне Досье контрагента для поля mnd-s:hasContractorCategoryRequest есть табличка. У нее в шапке написано **Проверяемые виды деятельности для Mondi, включая субподряд**
а надо вставить объект mnd-s:hasContractorCategoryRequest, то есть **Запрос на согласование контрагента**

**Comment by GilyazoMV** [comment]
Сделано.
