### ISSUE TITLE
Комплексный маршрут - проверка на запущенность

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#285]
В сети комплексного маршрута s-wf:net_complex_route нужно убрать (или обойти) проверку на запущенность процесса.
Мы решили проверять запущенность маршрута только на уровне кнопок. Пока, по-крайней мере.

Сделай как тебе удобно, можно удалить квадратик, можно его оставить, но чтоб он и при true и при false шел по процессу.

**Comment by xupyprmv** [comment]
@lexiqq проверь пожалуйста
