### ISSUE TITLE
Плашка с кнопками

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#286]
Добавить в шаблон Мероприятия Внутреннего аудита плашку с кнопками Удалить, Сохранить, Выдать задачу

**Comment by GilyazoMV** [comment]
Кнопочки добавил. Работает кривовато, так как при нажатии на кнопку сохранить у нас модальное окна переходит из режима edit  в view. затем нужно нажать либо ок либо еще что то, при этом вложеный шаблон(который лежит в основном документе) остается в режиме edit.
