### ISSUE TITLE
Добавление блока в Комплексный процесс

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#287]
Перед Согласованием сделать разветвление на квадрат Ознакомление, из которого далее нет стрелок. Основной процесс сразу уйдет на Согласование, а это ответвление путь хоть сколько висит.
Этот Ознакомление заменить ту самую Рассылку (Уведомиться) аналог СЭД.
Протянуть этот блок в Стартовую форму со всеми тонкостями.

**Comment by FluffyBear** [comment]
http://recordit.co/PYscTARymE

**Comment by FluffyBear** [comment]
@bychina Сделано. Надо проверить.
