### ISSUE TITLE
Согласование контрагента доделки

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#289]
1. Перенести из шаблона "Резолюция" две галочки "Решение о принятии, непринятии риска" и "Решение по экстренному согласованию контрагента" в шаблон Запроса на согласование контрагента

2. Переименовать label класса mnd-s:ContractorCategoryDecision из Резолюции в **Единый лист оценки**

3. Создать шаблоны 3-х резолюций mnd-s:ContractorCategoryDecisionPurchase, mnd-s:ContractorCategoryDecisionFinancial, mnd-s:ContractorCategoryDecisionOther. Оформить их создание и размещение аналогично другим резолюциям в форме Единого листа оценки.

4. Создать серверный скрипт, обрабатывающий сохранение индивидов класса mnd-s:ContractorCategoryDecision.
_Заполнить поле mnd-s:isOrganizationOk, если_
4.1. Если заполнены хотя бы два из трех галочки в Резолюциях, и они одинаковые, то mnd-s:isOrganizationOk = их значение.
4.2. Если заполнены хотя бы два из трех галочки в Резолюциях, и они разные, то mnd-s:isOrganizationOk = значению в СЭБ.
4.3. Если заполнены все трех галочки в Резолюциях, то mnd-s:isOrganizationOk = значению по большинству.
4.4. Если заполнены менее 2-х галочек в Резолюциях, то mnd-s:isOrganizationOk = значению в СЭБ.
Обрабатываемые галочки это поля 
mnd-s:isContractorOkTaxDepSummary из поля mnd-s:hasContractorCategoryDecisionTax
mnd-s:isContractorOkSecurityDepSummary из поля mnd-s:hasContractorCategoryDecisionSecurity
mnd-s:isContractorOkLegalDepSummary из поля mnd-s:hasContractorCategoryDecisionLegal
mnd-s:isContractorOkPurchaseDepSummary из поля mnd-s:hasContractorCategoryDecisionPurchase
mnd-s:isContractorOkFinancialDepSummary из поля mnd-s:hasContractorCategoryDecisionFinancial
mnd-s:isContractorOkOtherDepSummary из поля mnd-s:hasContractorCategoryDecisionOther

_Заполнить или перезаписать поле v-s:date текущей датой безусловно_

5. В маленьком шаблоне Итогового листа, который внутри Запроса, вывести все галочки резолюций, аналогично СЭБ. Итого их будет 6 + итоговая + дата Итоговой.

6. **Скрипт валидации** в форме запроса на согласование. 
Если поле mnd-s:hasContractorInteractionCategory=d:a188a7057-11d1-ce95-4e3c-3c4712b754f0, то 
1) поле v-s:expectedValueOfContract (ожидаемая сумма контракта) не обязательно.
2) в связанном Досье не проверяем обязательность файлов.

**Comment by GilyazoMV** [comment]
Тут все сделанно кроме этого :
1.
Создать серверный скрипт, обрабатывающий сохранение индивидов класса mnd-s:ContractorCategoryDecision.
Заполнить поле mnd-s:isOrganizationOk, если
4.1. Если заполнены хотя бы два из трех галочки в Резолюциях, и они одинаковые, то mnd-s:isOrganizationOk = их значению.
4.2. Если заполнены хотя бы два из трех галочки в Резолюциях, и они разные, то mnd-s:isOrganizationOk = значению в СЭБ.
4.3. Если заполнены все трех галочки в Резолюциях, то mnd-s:isOrganizationOk = значению по большинству.
4.4. Если заполнены менее 2-х галочек в Резолюциях, то mnd-s:isOrganizationOk = значению в СЭБ.

2.
в связанном Досье не проверяем обязательность файлов.

**Comment by karpovr** [comment]
Сделано

**Comment by bychina** [comment]
Изменение скрипта Заполнить или перезаписать поле v-s:date текущей датой безусловно.
Нужно поле v-s:date заполнять самой поздней датой создания из всех вложенных Резолюций, участвующих в расчете признка  mnd-s:isOrganizationOk

**Comment by bychina** [comment]
Изменение скрипта Заполнить или перезаписать поле v-s:date текущей датой безусловно.
Нужно поле v-s:date заполнять самой поздней датой создания из всех вложенных Резолюций, участвующих в расчете признка mnd-s:isOrganizationOk

**Comment by karpovr** [comment]
Сделано.
