### ISSUE TITLE
Процесс комплексной обработки для Запроса на согласование контрагента

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#290]
В шаблоне Запроса три кнопки "Первичная оценка", "Оценка рисков", "Запрос на блокировку". Все три стартую Комплексный процесс.

При нажатии на кнопку Первичная оценка вписываем в mnd-s:contractorRiskDecisionToAccept=false
При нажатии на кнопку Оценка рисков вписываем в mnd-s:contractorRiskDecisionToAccept=true
При нажатии на кнопку Запрос на блокировку вписываем в mnd-s:contractorRiskDecisionToAccept=false

**Запускается комплексный процесс:**

Если mnd-s:hasContractorInteractionCategory = "Блокировка" И mnd-s:contractorRiskDecisionToAccept=false, ТО
1. Согласование1 - d:mondi_position_70006692 (глав бух должность) и редактируемое с комментом "Сальдо расчетов, наличие просроченной задолженности"
2. Согласование2 - все люди, вычисленные ниже, редактируемое с комментом "Информация о контракте"
Найти все Контракты и Допы, у которых поле v-s:supplier = текущий документ / v-s:backwardTarget (Досье) / v-s:backwardTarget (Организация) 
У этих Контрактов и Допов собрать всех людей из поля mnd-s:supportSpecialistOfContract

3. Согласование3 - d:aaf889b74-6caa-8b21-5404-c6a9f91f8666 (ПУ). Редактируемое с комментом "Заключение о возможности блокировки"
4. Ознакомление - автор процесса с комментом "Согласование завершено"

Если mnd-s:hasContractorInteractionCategory != "Блокировка" И mnd-s:contractorRiskDecisionToAccept=false, ТО
тот процесс, который сейчас (НУ и СЭБ)

Если mnd-s:hasContractorInteractionCategory != "Блокировка" И mnd-s:contractorRiskDecisionToAccept=true, ТО
1. Согласование1 - d:aaf889b74-6caa-8b21-5404-c6a9f91f8666 (ПУ) Редактируемое
2. Поручение - d:mondi_position_71015289 (Фин директор), d:mondi_position_71020115 (Начальник УЗ) Редактируемое
3. Поручение - автор процесса с комментом "Оценка рисков произведена"

Если mnd-s:hasContractorInteractionCategory = "Блокировка" И mnd-s:contractorRiskDecisionToAccept=true, ТО
1. Поручение -  d:mondi_position_71015289 (Фин директор), d:mondi_position_71020115 (Начальник УЗ) Редактируемое
3. Поручение - автор процесса с комментом "Оценка рисков произведена"

**Comment by bychina** [comment]
всего 4 алгоритма но 3 кнопки.
Кнопка 1  "Первичная оценка" - второй алгоритм 
Кнопка 2  "Запрос на блокировку" - первыйи  алгоритм  
Кнопка 3  "Оценка рисков" - третий и четвертый  алгоритм
