### ISSUE TITLE
Доработка класса и шаблона Комментарий

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#292]
Добавить поле в класс Комментарий поле ссылка на любой документ системы v-s:linkedObject . Контрол: Поле поиска (с многоточием), плейсходдер: "Начните ввод и выбереты значение".
Поле множественное, Представление: Имя класса - label индивида.
Со временем можно добавить контрол (лупа), который откроет всплывающий поиск. 
Пока не добавлять никаких новых механизмов управления правами или группами, на объект, на который сослались.

**Comment by karpovr** [comment]
Готово d3142cdc
