### ISSUE TITLE
Валидация в Контракте и Доп соглашении

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#300]
В шаблонах Контракта и Доп соглашения есть валидация на проверку трех полей: 
Одно из полей v-s:customer или v-s:supplier или v-s:stakeholder должно быть заполнено Монди (d:org_RU1121003135)
Надо добавить в это правило "ИЛИ Монди Сейлз (d:org_RU7702347687)"

**Comment by GilyazoMV** [comment]
Готово Контракт и Доп соглашения. на 59 есть ужо.
