### ISSUE TITLE
Механизм пересчета валютных цен в рубли

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#312]
1. Расширить класс v-s:Price полем: "Сумма в Рублях по текущему курсу"
2. Спроектировать класс: Курс пересчета валют
3. Создать несколько индивидов этого класса и зафиксировать текущий курс для всех валют из нашего справочника , включая условные единицы. Лючще с фиксированными осмысленными id/
4. Добавить скрипт пересчета в шаблоне v-s:Price для поля "Сумма в Рублях по текущему курсу" - умножения текущей суммы на курс, подходящий по валюте в v-s:Price

**Comment by karpovr** [comment]
Сделано
