### ISSUE TITLE
2 и более модальных окна

### ISSUE THREAD

**Issue by GilyazoMV** [semantic-machines/veda#330]
1) зеленая кнопка которая открывает на весь экран работает но остается открытое модальное окно а подним открывается нужная нам  страница.
2) та же проблема с кнопкой развернуть на весь экран.

Возникает в Досье контрагента в котором мы открываем по синей лупе организацию в ней создаем филиал и пытаемся развернуть его на весь экран.

**Comment by karpovr** [comment]
fixed
