### ISSUE TITLE
Отдельная задача на Согласование

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#332]
Необходимо добавить отдельную задачу “на согласование” в кнопке “Выдать задачу”

**Comment by xupyprmv** [comment]
@FluffyBear Запили по аналогии с #169

**Comment by FluffyBear** [comment]
[Сделано](http://recordit.co/us49J5GXmV)

**Comment by xupyprmv** [comment]
@FluffyBear Замечательно!

Нужно добавить пару мелких фиксов:

В карточке задачи нужно поменять:
Ответственный -> Согласующий
Дата окончания -> Контрольный срок
"Количество" убрать

Добавить варианты ответа аналогичные вариантам ответа в Согласовании в комплексной 

https://github.com/semantic-machines/veda/blob/master/ontology/simple-workflow-module/simple-workflow-base.ttl#L792

только поменять `v-wf:DecisionDeclined` на `v-wf:DecisionRejected`

**Comment by FluffyBear** [comment]
@xupyprmv [Сделано](http://recordit.co/Wj6UGixi8A)

**Comment by xupyprmv** [comment]
@FluffyBear Красаучег!

@lexiqq Хозяйка, принимай работу

**Comment by lexiqq** [comment]
@xupyprmv @FluffyBear ок!
