### ISSUE TITLE
Доработка формы просмотра результатов поиска

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#343]
Необходимо реализовать возможность горизонтального скрола результатов поиска, помимо стандартного компонента. так как он всегда в конце списка, а при скроллировании вниз на него вообще не попасть, так как автоматом включается подгрузка следующей порции данных. И это тоже не удобно (по моему)

**Comment by karpovr** [comment]
Автоматическая подгрузка данных больше не делается. Пользователю нажимает кнопку "Еще результаты". При нажатии кнопки "Загрузить все результаты" происходит порционная загрузка всех результатов поиска в таблицу.
