### ISSUE TITLE
Считать все числа десятичными

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#344]
Отказаться от использования разных типов данных для чисел. Считать все числа типом float/double. Устранить "биение" чисел с плавающей точкой на сервере и клиенте.

**Comment by itiu** [comment]
я против решения считать все числа десятичными

**Comment by itiu** [comment]
на серверной стороне при работе скриптов остался код, из за которого происходит биение точности десятичных чисел

**Comment by itiu** [comment]
числа децимальные скриптами в ноль сбрасываются

**Comment by itiu** [comment]
серверная часть на c++ нестабильна

**Comment by itiu** [comment]
fix
