### ISSUE TITLE
Двойные учатники при заполнении Стартовой формы

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#348]
При автоматическом заполнении Стартовой формы Комплексного процесса, в алгоритме могут встречаться условия, при которых один и тот-же специалист (должность, назначение) вставляется в один уровень несколько раз. Например в Ознакомлении по Контрактам может попасть автор в качестве Специалиста по подготовке и Специалиста по сопровождению.
Можно проанализировать участников на одном уровне - и не добавлять дважды (трижды) одних и тех же.

**Comment by karpovr** [comment]
Сделано
