### ISSUE TITLE
Поведение клиента при завершении тикета

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#349]
При открытии браузера после долгого перерыва (тикет скорее всего просрочен) клиент позволяет работать, но при этом основное меню доступно, а контент страницы пустой. Не понятно - что происходит.
Нужно либо сообщение, либо переброс на страницу аутентификации, либо прозрачная аутентификация (для случаев когда это возможно)

**Comment by karpovr** [comment]
Исправлено.
