### ISSUE TITLE
Тест отправки / получения файлов в разных браузерах

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#356]
Разработать тест отправки и получения файлов с сервера для 3-х основных браузеров: GC, FF, IE11+.

**Comment by FluffyBear** [comment]
[Пока только для GC](https://github.com/semantic-machines/veda/blob/master/qa/testSendGet.js) В GC по умолчанию идет загрузка файла в папку, а в FF и IE нужно выбирать ее. Можно было бы просто получить файл в GC и только отправлять в других браузерах. Но в saucelabs не только для разных тестов, но и для каждого теста в разных браузерах создается новая несвязанная сессия. Буду решать эту проблему.

**Comment by karpovr** [comment]
Ok. c GC обычно всё и так хорошо. Я при разработке практически только на нем и тестирую. Оказалось, что есть много нюансов.
