### ISSUE TITLE
Назначения <-> Задачи

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#360]
1) Индексировать в задачах (DecisionForm) в атрибутах v-wf:from, v-wf:to значения типа v-s:Appointment (v-s:employee, v-s:occupation).

2) Убрать переключение активного назначения пользователя. Все действия пользователя выполняются от его назначения по-умолчанию.

3) Всем пользователям назначение по-умолчанию из SAP HR.

4) Реализовать в папках задач переключатели (фильтры) по доступным должностям (ролям) + персональные задачи.

5) Пересмотреть счетчики задач.

6) В процессах вернуть выдачу задач на назначения.

7) При выдаче задачи права выдавать: 
  * на Должность исполнителя (если исполнитель Должность)
  * на Должность и Персону ( если исполнитель - Назначение)

8) В качестве Автора документа DecisionForm  - указывать Назначение системной учетной записи.

9) Указывать дату создания задачи в сети.

**Comment by karpovr** [comment]
1. Сделано. b781d39278fbb549f7314d9c4208edca58d31ca7

**Comment by karpovr** [comment]
Пункты 8 и 9 за Валерой.

**Comment by itiu** [comment]
Пункты 8 и 9 решены в #382
