### ISSUE TITLE
Тестирование инбоксов и счетчиков задач

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#367]
Саша, надо сделать тест для счетчиков задач.

Для каждого получателя задач на сервере автоматически генерируется (и обновляется) общий счетчик задач, который в ходе работы пользователя с задачами может изменяться. 

Счетчик - это индивид у которого есть несколько свойств соответствующих различным видам задач. Сейчас это: число входящих задач, число исходящих задач, число выполненных задач, число входящих задач на текущую неделю.

В папках (входящие / исходящие / выполненные) сверху отображаются соответствующие числа. Необходимо проверять работоспособность счетчиков.

1) При получении задач счетчик входящих задач должен увеличиваться на 1 (автоматически по WS).
2) При ответе пользователя счетчик входящих задач должен уменьшаться на 1, счетчик выполненных задач должен увеличиваться на 1 (автоматически по WS).
3) При отправке задачи другому пользователю (например при запуске элементарного поручения) должен увеличиваться счетчик исходящих задач. При закрытии этой задачи получателем, счетчик должен уменьшиться на 1 (автоматически по WS).
4) Число в соответствующем счетчике должно быть равно общему количеству задач в папке. Например, находясь в Inbox общее количество задач в результатах должно соответствовать показаниям счетчика.

**Comment by FluffyBear** [comment]
Пока только одна задача. Добавлю еще.

**Comment by FluffyBear** [comment]
Добавил еще задач для разных пользователей. Осталось доработать проверку 4 пункта.

**Comment by FluffyBear** [comment]
@karpovr [Вроде готов](https://saucelabs.com/beta/tests/318f7c545afd4cd6a6b9594dad46175d/watch#661)

**Comment by karpovr** [comment]
Принято.
