### ISSUE TITLE
Указывание множества спецификаций для одного атрибута

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#37]
Было бы удобно, если бы можно было описывать один атрибут в нескольких спецификациях: например в спецификации только для чтения - указать все ридонли атрибуты шаблона, потом в  спецификации числовые - указать те из них, что являются числовыми и т.п.

**Comment by bychina** [comment]
При наличии спец инструмента по проектированию онтологий - возможно такая фича добавит удобство. Но при проектировании в ttl - по-моему, будет не удобно искать все "части" спецификации одного предиката.
