### ISSUE TITLE
Сети. Обработка отказа

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#370]
Для сети **s-wf:net_coordination** (Универсальный маршрут) добавить обработку полученного варианта ответа (s-wf:tr_taken_decision):

1. Для вариантов ответа v-wf:DecisionNotPerformed(не выполнено), v-wf:DecisionRejected(Отклонено), v-wf:DecisionNotForMe(Ошибочный исполнитель) направлять задачу "Принять отчет" тому, кто указан в переменной 'controller' (Контролер). 

Если переменная 'controller' пуста, то направлять задачу "Принять отчет" Инициатору (тому, кто запустил процесс, переменная 's-wf:var_initiator' )

2. Для вариантов ответа v-wf:DecisionAchieved(Выполнено), v-wf:DecisionAgreed(Согласовано), v-wf:DecisionConfirm(Подтверждено), v-wf:DecisionSign(Подписано) направлять задачу "Принять отчет" тому, кто указан в переменной 'controller' (Контролер). 

Если переменная 'controller' пуста, то задачу "Принять отчет" не направлять никому.

**Comment by bychina** [comment]
сделано
