### ISSUE TITLE
Сети. Варианты ответ задачи Отклонено.

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#371]
Для сети **s-wf:net_coordination** для квадратика **s-wf:nc_return_to_initiator**(обработка отказа или Отклонено):

1. убрать вариант ответа v-wf:DecisionAgreed(Согласовано).

2. добавить вариант ответа v-wf:DecisionAcceptMotivatedRefusal(Принять мотивированный отказ)

Обработку варианта ответа оставить прежней.

**Comment by bychina** [comment]
сделано
