### ISSUE TITLE
Запретить сохранение из Клиента объектов класса rdfs-s:resource

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#373]
1. В результате различных ошибок может возникать ситуация, при которой объект в Клиенте теряет свою принадлежность к классу или вообще все реквизиты, но ID при этом есть. На сервер он сохраняется с классом rdfs-s:resource. После этого очень сложно что-то с ним сделать пользователю, так как нет ни возможности открыть, ни возможности разобраться. При редактировании таких объектов в составе сложного - редактировать Клиент позволяет, но документ застревает в Черновике
2.  Нужно отличать на Клиенте ситуацию открытия объекта класса rdfs-s:resource и ситуации отсутствия объекта с таким ID в БД.

**Comment by karpovr** [comment]
Вообще странно, но сервер просто не должен их сохранять. У нас в системе нет права create для класса rdfs:Resource

**Comment by itiu** [comment]
Индивиды класса rdfs:Resource может сохранять только админы, этого достаточно для решения проблемы
