### ISSUE TITLE
Доработка процедуры формирования задачи в документообороте

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#382]
1. При формировании задачи из сети заполнять не только поле Дата создания, но и Автор.
Пусть автор будет константа: cfg:VedaSystem
2. В Клиенте при сохранении индивида Задача проверять, если поле Дата создания заполнено, а поле Автор не заполнено, то не нужно перетирать Дату создания текущей датой

**Comment by karpovr** [comment]
2. Сделал
