### ISSUE TITLE
доработка процедуры нумерации элементов пропусков заявки на пропуск

### ISSUE THREAD

**Issue by lav395** [semantic-machines/veda#384]
1. При наличии нескольких элементов пропуска(mnd-s:Pass) в заявке на пропуск(mnd-s:PassRequest) в момент сохранения происходит нумерация всех элементов, что может приводить к созданию одинаковых регистрационных номеров. Необходимо исключить подобные случаи.
2. Необходимо сохранить текущую нумерацию, т.к. требуется возможность создания пропуска без заявки.

**Comment by karpovr** [comment]
нумерация перенесена на сервер
