### ISSUE TITLE
Индексирование индивида в нескольких базах

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#386]
Индивиды типа s-wf:UserTaskForm (+ v-wf:DecisionForm) индексируются и в системной и в общей базе xapian, что может вызывать ошибки.

**Comment by itiu** [comment]
отключено индексирование  v-wf:DecisionForm в системной области:

vdi:index_01
  rdf:type vdi:ClassIndex ;
  vdi:forClass v-s:File ;
  vdi:forClass v-wf:Process ;
#  vdi:forClass v-wf:DecisionForm ;
  vdi:forClass v-s:Membership ;
  vdi:forClass v-s:PermissionStatement ;
  vdi:indexed_to "system" ;
.
