### ISSUE TITLE
Отсутствует поле v-s:creator  в объектах v-wf:DecisionForm, s-wf:UserTaskForm

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#394]
Отсутствует поле v-s:creator  в объектах v-wf:DecisionForm, s-wf:UserTaskForm
Скорее всего связано с последними исправлениями в клиенте при обработке Ответов на задачи.
На поле  v-s:creator  заложена логика: например при перенаправлении задачи - отображается от кого перенаправлена.
В журнале - кто реально ответил

**Comment by karpovr** [comment]
Да, только это не правильно указывать автором формы ответа на задачу человека, которому она адресована. В случае перенаправления автор должен считываться не из s-wf:UserTaskForm, а из индивида принятого решения  (v-wf:takenDecision)
