### ISSUE TITLE
Баг индексации

### ISSUE THREAD

**Issue by brutalp** [semantic-machines/veda#398]
Индексация не проходит, когда в шаблоне есть вложенный шаблон, но он по какой-то причине не сохранился. Хотя сохранение основного шаблона произошло. Замечено было в заявке на ОЗМ. При нажатии на синий плюс у нас открывалось поп ап окно, в котором вложенный шаблон с "Ориентировочная стоимость". После сохранение всего документа, сохранялась "Заявка на ОЗМ", "Элемент заявки на ОЗМ", но не сохранялась "Ориентировочная стоимость", которая находилась в "Элемент заявки на ОЗМ". В следствии чего "Элемент заявки на ОЗМ" не попадал в индекс.

**Comment by itiu** [comment]
В данном случае нарушен порядок сохранения документов, сначала сохраняется внутренний а затем наружний, по этому поле внутреннего документа v-s:parent.rdf:type не может быть проиндексированно
