### ISSUE TITLE
BL: обеспечить возможность изменения значений определенных предикатов из BL в BT

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#413]
При создании объекта класса v-s:BackwardLink(BL) указать имена предикатов, значения которых в целевом объекте ссылки будут заменены на значения из ссылки.

Постановка:
1) Определить новое свойство в классе BL, смысл которого - указание перечня свойств в ссылке, значения которых заменят собой значения одноименных свойств в целевом объекте. Наименование предиката: v-s:backwardReplace

2) Реализовать соответствующий код в серверном скрипте, обрабатывающем BL ( cfg:Event_16 ).

**Comment by miniJoker** [comment]
Закоммитил
