### ISSUE TITLE
Запланированные события

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#430]
Для класса v-s:ScheduledAction написать скрипт обработчик.

Скрипт ежедневно пробегает по всем индивидам класса v-s:ScheduledAction.

Если v-s:dateToPlan меньше равна текущей и v-s:dateToFact пусто, то обрабатываем документ.

Если (v-s:dateToPlan - v-s:hasPeriod) равно текущая дата, то формируем и отправляем задачу, у которой

Описание берем из поля v-s:description
Ответстенный из поля  v-s:responsible
Контроллер из поля v-s:controller
Контрольный срок из поля v-s:dateToPlan

Вписать текущую дату в поле v-s:dateToFact.

Справчоник v-s:Period

Час - d:jsc4p8dq5u4fm1sumekuifkw7r 
День - d:z8r34mi5y8rl8m4kbo3q69uw5d
Неделя - d:a21t5y3pswuewm8ohjexiqtxscr
Месяц - d:pqauzdiqyls7pzrawelnh2zwj3
Квартал - d:a28m44dm9yw04j7hf69r4i40sn5
Год - d:p699yrkgnd7bamjaqwx305o5hi

**Comment by ValeriyBushenev** [comment]
.
