### ISSUE TITLE
Порядок обработки фактов редактирования для cfg:Administrator

### ISSUE THREAD

**Issue by bychina** [semantic-machines/veda#437]
Установить такой порядок обработки фактов редактирования для учетной записи 
cfg:AdministratorAppointment   rdf:type v-s:Appointment
cfg:AdministratorAccount   rdf:type v-s:Account 
1. При изменении объекта в Клиенте (в любом режиме: в шаблоне в json, при работе скрипта)
Не подменять в Модели клиента поля: Автор, Дата создания, Редактор, Дата редактирования.
При этом эти поля могут быть изменены при самой операции редактирования.
2. При серверной обработке Автоверсионных классов.
Не создавать версию. По сути игнорировать скрипт версионности.

**Comment by karpovr** [comment]
Реализовано
