### ISSUE TITLE
Отображение файлов в аттрибутивном поиске

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#44]
В результатах аттрибутивного поиска, если реквизит типа v-s:File, то отображать его реквизит v-s:fileName.
Или где-то в шаблоне для файлов надо написать скрипт, которые rdfs:label = v-s:fileName

**Comment by karpovr** [comment]
Исправлено в 5b1c044ac6bd4b65fee90a698882e8e5d3d16c51
