### ISSUE TITLE
Создать новый нумератор по типу+году+Организации

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#440]
Создать новый нумератор в зоне v-s, который создает пространство нумератора по типу, году и организации. 
Организацию смотреть по полю v-s:correspondentOrganization внутри нумеруемого документа.
Порядковый номер выглядит обычно 1, 2, 3...

За основу можно взять нумератор v-s:RegistrationNumberSimpleNumerationYear
Назвать новый нумератор можно v-s:RegistrationNumberSimpleNumerationYearOrganization или как-то по-другому.

Проверять можно на локале в зоне kat. Там я уже прописала для Исх и Вход писем, чтоб в рег запись протягивалось поле v-s:correspondentOrganization из индивида v-s:Correspondent.

**Comment by karpovr** [comment]
commit: 1eec9d6d
