### ISSUE TITLE
Модификация скриптов при сохранении

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#47]
Сделать возможность проводить серверные проверки, до сохранения документа. Уведомлять клиента о невозможности сохранения документа, если сохранение невозможно.

Например: разделить скрипты на "до сохранения" и "после созранения". Первая группа может вернуть несколько ошибок. В этом случае сохранение не производить, а данные об ошибках отправить на клиент.

**Comment by itiu** [comment]
Думаю что event before, является опасной конструкцией, которая может приводить к малопонятным ситуациям когда документ не будет сохранятся. Предлагаю вместо этого прикреплять к документу информацию об ошибке и указанием что документ плохой, например так можно поступать при валидации.
