### ISSUE TITLE
Кнопка вызова простых единичных задач

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#50]
Нужна кнопка на всех документах с выпадающим списком стандартных задач:
Задать вопрос, На согласование, На подписание, На рассмотрение, Выдать поручение, На ознакомление.
При этом кнопка отправить должна быть отдельно, а список стандартных задач по выпадающему треугольнику справа (как сейчас в СЭДе)

**Comment by xupyprmv** [comment]
Чтобы добавить список с линками на базовае процессы достаточно разместить элемент с идентификатором `standard-tasks` на форму (Для generic шаблонов кнопка появлсяется автоматически). Например:

	    <div class="btn-group dropup">
			<button type="button" class="action btn btn-warning view edit -search -draft -version" id="send1" aria-haspopup="true" aria-expanded="false">
		      	<span about="v-b:Send" property="rdfs:label"></span> 			
            </button>
			<button class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
				<span class="caret"></span>
			</button>	    
			<ul class="dropdown-menu" id="standard-tasks">
			</ul>
		</div>
