### ISSUE TITLE
Scope для скриптов

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#56]
Механзм пометки скриптов, чтоб они отрабатывали или не отбрабатывали на разных страницах (view edit search)

**Comment by karpovr** [comment]
Это можно делать на в самом скрипте. Например написать условие с проверкой значения переменной "mode". Эта переменная передается внутрь скрипта шаблона. Значение переменной содержит значение режима отображения индивида ("view", "edit", "search").

**Пример:**
```javascript
<div>Шаблон</div>
<script>
  if (mode === "view") { alert ("mode = view"); }
  if (mode === "edit") { alert ("mode = edit"); }
  if (mode === "search") { alert ("mode = search"); }
</script>
```
