### ISSUE TITLE
Валидация в идее

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#61]
При сохранении шаблона mnd-s-asppd:Idea, хлотя бы одно из полей mnd-s:hasCheckedDepartment или mnd-s-asppd:hasContractKindForIdea должно быть заполнено.

**Comment by xupyprmv** [comment]
Также обновлен IdeaTemplate

**Comment by lexiqq** [comment]
Убрать эту валидацию. Так как принято решение, что обязательным будет только одно поле mnd-s:hasCheckedDepartment, а это решается спецификацией.

**Comment by lexiqq** [comment]
Убрать эту валидацию. Так как принято решение, что обязательным будет только одно поле mnd-s:hasCheckedDepartment, а это решается спецификацией.
