### ISSUE TITLE
внести изменения в функцию toggleEffects для финансовых эффектов в идее

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#65]
function toggleEffects() {

IF individual["mnd-s-asppd:hasIdeaStatus"][0].id === "mnd-s-asppd:IdeaStatusReview",
то в поле hasFinancialEffectForIdea видимые все поля, но
поля mnd-s-asppd:hasFactMonth1Effect - mnd-s-asppd:hasFactMonth12Effect только чтение

IF individual["mnd-s-asppd:hasIdeaStatus"][0].id === "mnd-s-asppd:IdeaStatusIntroduced")),
то в поле hasFinancialEffectForIdea видимые все поля, но
поля mnd-s-asppd:hasPlanYearEffect и mnd-s-asppd:hasPlanOnceEffect только чтение

При других статусах поле hasFinancialEffectForIdea не видимо целиком

}

**Comment by xupyprmv** [comment]
https://bitbucket.org/semantic_machines/dmsc/commits/f5a535f6d4f7085d2c0b87e956e2c531ae9b7608

**Comment by lexiqq** [comment]
Распространить эту функцию еще и на событие нажатие "плюсика" для реквизита hasFinancialEffectForIdea.
Так как для всех добавленных новых эффектов этот скрипт не отрабатывает

**Comment by xupyprmv** [comment]
Получилось сделать только через setTimeout
