### ISSUE TITLE
После нажатия на кнопку "Отправить" в задаче и стартовой форме после успешной отправки отображать пользователю позитивное сообщение.

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#71]

**Comment by xupyprmv** [comment]
После отправки вернуть на просмотр документа.

**Comment by lexiqq** [comment]
Возможно, лучше открывать страницу с отдельным классом, под который мы сверстаем шаблон, передавать ему id документа. И он через 5 секунд будет закрываться и переходить на вью документа по id.
