### ISSUE TITLE
bug в поисковом запросе

### ISSUE THREAD

**Issue by lexiqq** [semantic-machines/veda#76]
в поиске типа
('rdfs:type'=='mnd-s-asppd:Kpi') && ('rdfs:label' == '+Производство +готовой +продукции' || 'rdfs:label' == 'Лесообеспечение')
не фильтруется по rdfs:type

**Comment by itiu** [comment]
нужно поправить запрос:
('rdf:type'=='mnd-s-asppd:Kpi') && ('rdfs:label' == '+Производство +готовой +продукции' || 'rdfs:label' == 'Лесообеспечение')
