### ISSUE TITLE
в базовом проекте veda, присутствуют артефакты третьих проектов 

### ISSUE THREAD

**Issue by itiu** [semantic-machines/veda#80]
в базовом проекте veda, присутствуют артефакты третьих проектов:

- картинка от mondi
- меню - управление проектами

**Comment by xupyprmv** [comment]
@itiu, @karpovr я думаю что нужно подойти к этой задаче более глобально. Я создал  #83 и #84.

**Comment by itiu** [comment]
public/js/browser/util.js

 +					if (individual['rdf:type'][0].id == 'mnd-s-asppd:IdeaRouteStartForm') {
