### ISSUE TITLE
Net Editor: добавлять новые элементы в consistOf

### ISSUE THREAD

**Issue by xupyprmv** [semantic-machines/veda#82]
Создаваемые элементы добавлять в `v-wf:consistsOf`

**Comment by xupyprmv** [comment]
@itiu на данный момент в обработчиках событий добавления/удаления `State` (К которым относятся `Task` и `Condition`) и `Flow` уже реализовано добавление/удаление элементов в/из `v-wf:consistsOf`. Какие элементы ещё нужно хранить в `v-wf:consistsOf`?

**Comment by itiu** [comment]
@xupyprmv Все элементы создаваемые редактором следует добавлять в v-wf:consistsOf, таким образом мы сможем выгрузить в один файл все что было сделано в рамках данной сети (путем выгрузки в ttl индивида v-wf:Net)
