### ISSUE TITLE
Блокировать поле v-s:password в get запросах

### ISSUE THREAD

**Issue by karpovr** [semantic-machines/veda#89]

**Comment by itiu** [comment]
для решения этой задачи был добавлен метод:

    /**
       Доверенная аутентификация
       Params:
                ticket = имя пользователя, входящего в группу [cfg:SuperAdmin]
                login = имя пользователя, кому будет выдан новый тикет

       Returns:
                экземпляр структуры Ticket
     */
    Ticket get_ticket_trusted(string ticket, string login);

**Comment by itiu** [comment]
пароль следует вынести в отдельный индивид.
в связи с этим, текущая задача закрывается и открывается новая
